### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by niradler** [Omar-Belghaouti/react-help-create#1]
Hi, i think the most powerful feature will be to manage the component template, something like creating ".template" folder and when you run rhc create -c <component_name> --template page
the component will be generated from the page template

**Comment by Omar-Belghaouti** [comment]
@niradler glad you found it helpful. I think the same, this can be very helpful and since it's given a default template to create a component or page, it can also be used with a user defined template. Thanks for this idea, and it'll be in the next release! 🚀

**Comment by Omar-Belghaouti** [comment]
@niradler glad you found it helpful. I think the same, this can be very helpful and since it's given a default template to create a component or page, it can also be used with a user defined template. Thanks for this idea, and it'll be in the next release! 🚀

**Comment by Omar-Belghaouti** [comment]
@niradler I have added the template option, I hope you like it. And feel free to reopen the issue if it doesn't help with your needs 😉
